### ISSUE TITLE
it downloads only overrides, not mods 

### ISSUE THREAD

**Issue by m00nlygreat** [DanSnow/minecraft-modpack-downloader#1]
i tried this and it only downloads overrides, not mods
![image](https://user-images.githubusercontent.com/29726529/176692987-86461d6f-be9a-4e07-bf14-d266c1c8462d.png)

why is it..? 

thanks in advance

**Comment by DanSnow** [comment]
Looks like the underlying API that is used in this tool is unavailable. I'm not sure when will it be back. Currently, I'll recommend you to try https://github.com/gorilla-devs/ferium.

**Comment by m00nlygreat** [comment]
>  Thanks. I have tried ferium, and it worked so well
